### ISSUE TITLE
Diagnosing multi-threading segfaults upon upgrading to 3.1.9

### ISSUE THREAD

**Issue by LTLA** [emscripten-core/emsdk#1042]
**tl;dr** Updating to 3.1.9 resulted in the introduction of a sporadic segfault in my multi-threaded code.

**Minimal reproducible example**: https://github.com/LTLA/h5wasm-pthreads-MRE

**Long story:**

My application links against an Emscripten build of the HDF5 library (see https://github.com/usnistgov/libhdf5-wasm). It also uses Emscripten's pthreading support for parallelization. So far, both of these features have happily co-existed in the same Wasm binary... until 3.1.9, at which point the app began to experience a variety of strange and sporadic run-time errors related to the threading.

The MRE repository contains the boiled-down version of the problem. In short, linking to the HDF5 static library is sufficient to cause rare failures in the threaded code, even though the HDF5 functions are never called (in either the parallel or serial regions). In fact, in the MRE, the threads don't do anything at all; the segfaults occur during the creation of the thread, looking like this:

```
RuntimeError: Aborted(segmentation fault)
    at abort (file:///Users/luna/Programming/js/h5-mre/build/minimal.js:1506:10)
    at segfault (file:///Users/luna/Programming/js/h5-mre/build/minimal.js:924:2)
    at SAFE_HEAP_LOAD_i32_1_U_1 (<anonymous>:wasm-function[605]:0x10071)
    at _emscripten_thread_sync_code (<anonymous>:wasm-function[226]:0x51ea)
    at _emscripten_yield (<anonymous>:wasm-function[241]:0x5a52)
    at emscripten_futex_wait (<anonymous>:wasm-function[227]:0x52cd)
    at __timedwait_cp (<anonymous>:wasm-function[284]:0x7291)
    at __timedwait (<anonymous>:wasm-function[285]:0x72f8)
    at __pthread_mutex_timedlock (<anonymous>:wasm-function[310]:0x7d74)
    at __pthread_mutex_lock (<anonymous>:wasm-function[308]:0x7c62)
```

Now, I don't think this is completely Emscripten's fault, because the HDF5 library is notoriously finicky w.r.t. any parallelization. My current hypothesis about the nature of this bug (repeated from usnistgov/libhdf5-wasm#1) is that:

1. The HDF5 library is setting some global state when it starts up.
2. When a Emscripten-managed web worker is asked to execute something for the first time, it runs this start-up code. (It seems that the actual initialization of the worker doesn't do all of the Wasm set-up, if my interpretation of the `*.worker.js` file is correct.)
3. If you have enough workers that are launched at the same time, all of them are fighting with each other to perform the global set-up. This causes some kind of corruption in the SharedArrayBuffer, resulting in a segfault.

This leaves me with two questions:

- Is my hypothesis correct? I'd like to figure out what Emscripten included from the HDF5 static library to see what exactly what it was doing in the Wasm binary, but unfortunately my wat-reading skills are not up to scratch; any help would be appreciated.
- Why does this occur in 3.1.9 and not in 3.1.8? I see some changes related to proxying to threads but I don't know if that's relevant.

My current workaround is to wait for thread set-up to complete (by polling on some atomic flags) before creating the next thread. This seems to work but I would be a lot more confident in it if I understood why.

**Comment by sbc100** [comment]
It seems likely that #16531 is the cause although its not clear to me why.

Can we see the full stacktrace?  Do you know on which thread the segfault occurs?   Are you building with dynamic linking (-sMAIN_MODULE)?  Are you loading side modules?
