### ISSUE TITLE
Cannot use optional chaining in pre-js or post-js with `-O2` or higher

### ISSUE THREAD

**Issue by bbrk24** [emscripten-core/emsdk#1201]
When compiling with `-O2` or higher and `--pre-js` or `--post-js`, the provided JavaScript file(s) may not use [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining). If I try, I get the following error (with some paths redacted):

```
C:\[...]\emsdk\upstream\emscripten\third_party\terser\terser.js:21475
          var ret = node != null ? MOZ_TO_ME[node.type](node) : null;
                                                       ^

TypeError: MOZ_TO_ME[node.type] is not a function
    at from_moz (C:\[...]\emsdk\upstream\emscripten\third_party\terser\terser.js:21475:56)
    at Object.From_Moz_LogicalExpression [as LogicalExpression] (eval at map (C:\[...]\emsdk\upstream\emscripten\third_party\terser\terser.js:21461:23), <anonymous>:9:8)
    at from_moz (C:\[...]\emsdk\upstream\emscripten\third_party\terser\terser.js:21475:56)
    at Object.From_Moz_IfStatement [as IfStatement] (eval at map (C:\[...]\emsdk\upstream\emscripten\third_party\terser\terser.js:21461:23), <anonymous>:7:12)
    at from_moz (C:\[...]\emsdk\upstream\emscripten\third_party\terser\terser.js:21475:56)
    at Array.map (<anonymous>)
    at Object.From_Moz_BlockStatement [as BlockStatement] (eval at map (C:\[...]\emsdk\upstream\emscripten\third_party\terser\terser.js:21461:23), <anonymous>:7:14)
    at from_moz (C:\[...]\emsdk\upstream\emscripten\third_party\terser\terser.js:21475:56)
    at Object.From_Moz_IfStatement [as IfStatement] (eval at map (C:\[...]\emsdk\upstream\emscripten\third_party\terser\terser.js:21461:23), <anonymous>:8:7)
    at from_moz (C:\[...]\emsdk\upstream\emscripten\third_party\terser\terser.js:21475:56)
emcc: error: 'C:/[...]/emsdk/node/14.18.2_64bit/bin/node.exe C:\[...]\emsdk\upstream\emscripten\tools\acorn-optimizer.js C:\[...]\AppData\Local\Temp\emscripten_temp_kwxa_obk\out.js AJSDCE minifyWhitespace -o C:\[...]\AppData\Local\Temp\emscripten_temp_kwxa_obk\out.jso1.js' failed (returned 1)
```

**Comment by sbc100** [comment]
Most likely this is similar to #18968.  I think @kripken is probably best place to take a look.

**Comment by kripken** [comment]
I believe that `is not a function` means that the version of terser that we use does not support that AST type. It's very likely that upstream terser does, so an upgrade would be needed.

**Comment by sbc100** [comment]
We have since upgraded terser and use a lot optional chaining in emscripten itself.
