### ISSUE TITLE
emsdk just stopped working

### ISSUE THREAD

**Issue by evanw** [emscripten-core/emsdk#256]
Our CI infrastructure just broke because a download is missing:

```
$ git clone https://github.com/emscripten-core/emsdk.git
Cloning into 'emsdk'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 1393 (delta 13), reused 10 (delta 4), pack-reused 1367
Receiving objects: 100% (1393/1393), 745.20 KiB | 4.03 MiB/s, done.
Resolving deltas: 100% (881/881), done.

$ cd emsdk/

$ ./emsdk update-tags
Fetching all tags from Emscripten Github repository...
Done. 160 tagged releases available, latest is 1.38.32.
Fetching all tags from Binaryen Github repository...
Done. 87 tagged Binaryen releases available, latest is 1.38.32.
Fetching emscripten-releases repository...
Cloning into 'emsdk/releases'...
remote: Total 1057 (delta 243), reused 1057 (delta 243)
Receiving objects: 100% (1057/1057), 555.16 KiB | 1.52 MiB/s, done.
Resolving deltas: 100% (243/243), done.
Fetching latest changes to the branch 'master' for 'emsdk/releases'...
Already up to date.
Successfully updated and checked out branch 'master' on repository 'emsdk/releases'
Current repository version: "Thu, 30 May 2019 22:04:56 +0000 95a2fd5dd490c7ffd680f4de8a1aef81fe478ea9"
Fetching all precompiled tagged releases..
Downloading: emsdk/llvm-tags-32bit.txt from https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/osx_32bit/index.txt
Downloading: emsdk/llvm-tags-64bit.txt from https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/osx_64bit/index.txt, 2661 Bytes

$ ./emsdk install sdk-1.37.20-64bit
Installing SDK 'sdk-1.37.20-64bit'..
Installing tool 'clang-e1.37.20-64bit'..
Downloading: emsdk/zips/emscripten-llvm-e1.37.20.tar.gz from https://storage.googleapis.com/webassembly/emscripten-releases-builds/old/mac/emscripten-llvm-e1.37.20.tar.gz, 223019865 Bytes
Unpacking 'emsdk/zips/emscripten-llvm-e1.37.20.tar.gz' to 'emsdk/clang/e1.37.20_64bit'
Done installing tool 'clang-e1.37.20-64bit'.
Installing tool 'node-4.1.1-64bit'..
Error downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v4.1.1-darwin-x64.tar.gz': HTTP Error 404: Not Found
Traceback (most recent call last):
  File "./emsdk", line 2648, in <module>
    sys.exit(main())
  File "./emsdk", line 2630, in main
    success = tool.install()
  File "./emsdk", line 1522, in install
    success = tool.install()
  File "./emsdk", line 1538, in install
    success = download_and_unzip(url, self.installation_path(), download_even_if_exists=download_even_if_exists, filename_prefix=filename_prefix)
  File "./emsdk", line 1107, in download_and_unzip
    assert received_download_target == download_target
AssertionError
```

The file https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v4.1.1-darwin-x64.tar.gz is missing.

We're guessing this might be related to #254? Is there something we need to change about our use of emsdk?

**Comment by kripken** [comment]
Thanks for filing - this is related to our migration away from the old mozilla infrastructure to the new chromium stuff.

At this point we should have full support for the last several versions, but not as far back as what you're trying to download here, which is 1.37.20 (which is almost 2 years ago). I'm not sure we've decided how far back we want to support older builds - @dschuff, what do you think?

In the immediate term, you can use a slightly older emsdk (basically, from yesterday), which will still look on the old servers. However, that will stop working when mozilla takes those down.

**Comment by kripken** [comment]
@evanw - I uploaded the necessary files for 1.37.20 and tested it locally on linux, where it works. Hopefully that fixes things for you. That may not be enough for even earlier versions though.

Btw, why are you still on that old version?

**Comment by evanw** [comment]
Ah ok, that's good to know. Thanks for looking into it. We didn't realize there wasn't a stability guarantee around emscripten releases. We're currently considering forking emsdk for stability.

We're still on this old version because upgrading to a newer version of emscripten slows down our builds. I filled #7712 about this in the past. I tried profiling the compiler like you suggested but unfortunately wasn't able to get a speedup.

I'm hopeful that emscripten will eventually become faster again when LLVM is used to generate WebAssembly instead of asm2wasm. But we will likely wait a while after that lands before upgrading while the bugs are still being worked out.

**Comment by kripken** [comment]
I would say we've passed the biggest period of instability, as we are mostly done with the infrastructure migration at this point. If what you need works after that last fix, then it should continue working for a very long time.

About the slow compilation, yeah, I'm not surprised compile times slowly get worse (LLVM and other optimizers gain more optimizations, etc.). And yeah, the LLVM wasm backend should fix that (link is 7x faster on BananaBread, for example.)
