### ISSUE TITLE
emconfigure failing on windows 10

### ISSUE THREAD

**Issue by angupt** [emscripten-core/emsdk#399]
I am trying to use emsdk on windows and install it as per guide instruction but when I run emconfigure cmake command, I am getting following error message.

```
emconfigure cmake
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\git_code\emsdk\emsdk\upstream\emscripten\emconfigure.py", line 61, in <module>
    sys.exit(run())
  File "C:\Users\admin\Desktop\git_code\emsdk\emsdk\upstream\emscripten\emconfigure.py", line 54, in run
    shared.Building.configure(sys.argv[1:])
  File "C:\Users\admin\Desktop\git_code\emsdk\emsdk\upstream\emscripten\tools\shared.py", line 1713, in configure
    run_process(args, stdout=stdout, stderr=stderr, env=env)
  File "C:\Users\admin\Desktop\git_code\emsdk\emsdk\upstream\emscripten\tools\shared.py", line 184, in run_process
    proc = Popen(cmd, *args, **kw)
  File "C:\Users\admin\Desktop\git_code\emsdk\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Users\admin\Desktop\git_code\emsdk\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

I am using windows 10 64 bit and executing the command from cmd

**Comment by kripken** [comment]
Is cmake present? That is the error I would expect if it can't find the cmake executable (but it could also be something else, I'm not sure).

**Comment by angupt** [comment]
@kripken thanks for pointing me in right direction.

**Comment by subbiah95** [comment]
When I run the emconfigure ,I get he following error.

emconfigure ../node_modules/libvpx/configure \
    --target=generic-gnu

Traceback (most recent call last):
  File "D:\emsdk\fastcomp\emscripten\emconfigure.py", line 26, in <module>
    from tools import shared
  File "D:\emsdk\fastcomp\emscripten\tools\shared.py", line 744, in <module>
    CLANG_CC = os.path.expanduser(build_clang_tool_path(exe_suffix('clang')))
  File "D:\emsdk\fastcomp\emscripten\tools\shared.py", line 621, in build_clang_tool_path
    return os.path.join(LLVM_ROOT, tool)
  File "c:\python27\lib\ntpath.py", line 65, in join
    result_drive, result_path = splitdrive(path)
  File "c:\python27\lib\ntpath.py", line 115, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()

@kripken , any idea about this

**Comment by sbc100** [comment]
Strange, that means LLVM_ROOT must be None, and I am very surprised that is possible.

Can you run `./emcc -v` and see what it prints.  Also take a look at your emscripten config file and see what LLVM_ROOT is set to.
