### ISSUE TITLE
TypeError: wasm function signature contains illegal type

### ISSUE THREAD

**Issue by mbovel** [emscripten-core/emsdk#476]
Hello,

I think I found a problem with the last version:

```
$ ./emsdk install 1.39.13
...
$ source emsdk_env.sh
...
$ emcc --version
emcc (Emscripten gcc/clang-like replacement) 1.39.13
...
$ emcc -g2 -O3 -s EXIT_RUNTIME=1 -s STANDALONE_WASM -o gettime.js gettime.c
...
$ node gettime.js
exception thrown: TypeError: wasm function signature contains illegal type,TypeError: wasm function signature contains illegal type
    at wasm-function[49]:41
    at wasm-function[52]:40
    at wasm-function[7]:80
    at wasm-function[8]:164
    at wasm-function[9]:20
    at Module.__start (/Users/mbovel/emsdk/gettime.js:2187:34)
    at callMain (/Users/mbovel/emsdk/gettime.js:2438:5)
    at doRun (/Users/mbovel/emsdk/gettime.js:2503:23)
    at run (/Users/mbovel/emsdk/gettime.js:2518:5)
    at runCaller (/Users/mbovel/emsdk/gettime.js:2420:19)
```

which was not present in version 1.39.8:

```
$ ./emsdk install 1.39.8
...
$ source emsdk_env.sh
...
$ emcc --version
emcc (Emscripten gcc/clang-like replacement) 1.39.8 (commit 6dd96f1f2c918edefbce9fe8723ea280aa2ac8a9)
...
$ emcc -g2 -O3 -s EXIT_RUNTIME=1 -s STANDALONE_WASM -o gettime.js gettime.c
...
$ node gettime.js
881000
```

Content of `gettime.c`:

```c
#include <stdio.h>
#include <sys/time.h>

int main(int argc, char* argv[]) {
	struct timeval t;
	gettimeofday(&t, NULL);
	printf("%lu", (unsigned long)t.tv_usec);
	return 0;
}
```

` wasm-function[49]` contains a call to `wasi_snapshot_preview1.clock_time_get`.

Might it have something to do with `wasi_snapshot_preview1.clock_time_get` and its multiple return types?

Have a nice day!

**Comment by sbc100** [comment]
This seems to be relates to STANDALONE_WASM and JS function signature legalization that is supposed to handle import/export of function that that 64bit arguments. 

It doesn't reproduce without STANDALONE_WASM, which I believe is becasue the normal non-standalone JS build implements clock_gettime in JS. 

I'm bisecting this now.

**Comment by sbc100** [comment]
I bisected this issue to #10530.   @kripken let me know if you want to take this or I can keep investigating.

**Comment by sbc100** [comment]
This TODO explains why its not working: https://github.com/emscripten-core/emscripten/blob/ab28e4897b71c41752ff55a7e22b3bbd4a3a79fe/src/library_wasi.js#L100

**Comment by kripken** [comment]
Thanks @sbc100 , yeah, that's the issue. We can't legalize the wasm in standalone mode since we want it to run in a wasm VM. But then the JS which requires legalization can't work.

@mbovel As mentioned in the comment there, you can avoid legalization by using BigInt support, which has landed, just build with `-s WASM_BIGINT` and then enable the feature in the JS shell (in d8, `d8 --wasm-staging`, in node 12.91.1, `node --experimental-wasm-bigint`).

**Comment by sbc100** [comment]
Is there some way we can detect and report this issue on load?    

If we really want to fix it guess we could generate wasm wrappers on the fly that does the legalization?  Might not be worth it given bigint is coming?

**Comment by mbovel** [comment]
Thank you for looking into this so quickly.

For anyone who would not know what *legalization* is: https://github.com/WebAssembly/binaryen/blob/master/src/passes/LegalizeJSInterface.cpp#L18

Running with `node --experimental-wasm-bigint gettime.js` works better in that it does not throw a `TypeError` exception.

However, unfortunately, it always prints `0`:

```
$ node --experimental-wasm-bigint gettime.js
0
```

Would you know why?

**Comment by kripken** [comment]
@mbovel that's weird, it prints nonzero outputs for me with both d8 and that version of node. What version are you on?

@sbc100 

> Is there some way we can detect and report this issue on load?

We could perhaps refuse to emit JS at all in this case. Or make the JS immediately error if one tries to run it.

> If we really want to fix it guess we could generate wasm wrappers on the fly that does the legalization? Might not be worth it given bigint is coming?

Yeah, not worth a big project to work around this I think, given BigInt support is shipping.

**Comment by mbovel** [comment]
> What version are you on?
12.9.1

Compiling without the `-O3` and running from node throws `Runtime error: The application has corrupted its heap memory area (address zero)!`.

<details><summary>All commands I ran</summary>
<p>

```
~ 
> git clone https://github.com/emscripten-core/emsdk
Cloning into 'emsdk'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 1866 (delta 4), reused 4 (delta 1), pack-reused 1851
Receiving objects: 100% (1866/1866), 1.02 MiB | 2.07 MiB/s, done.
Resolving deltas: 100% (1181/1181), done.

~ 
> cd emsdk

~/emsdk 
> pbpaste > gettime.c

~/emsdk 
> cat gettime.c
#include <stdio.h>
#include <sys/time.h>

int main(int argc, char* argv[]) {
	struct timeval t;
	gettimeofday(&t, NULL);
	printf("%lu", (unsigned long)t.tv_usec);
	return 0;
}

~/emsdk 
> ./emsdk install 1.39.13
...

~/emsdk 
> which node
/Users/mbovel/emsdk/node/12.9.1_64bit/bin/node

~/emsdk 
> node --version
v12.9.1

~/emsdk 
> emcc -g2 -O3 -s EXIT_RUNTIME=1 -s STANDALONE_WASM -o gettime.js gettime.c

~/emsdk 
> node --experimental-wasm-bigint gettime.js
0

~/emsdk 
> emcc -s EXIT_RUNTIME=1 -s STANDALONE_WASM -o gettime.js gettime.c

~/emsdk 
> node --experimental-wasm-bigint gettime.js
Runtime error: The application has corrupted its heap memory area (address zero)!
Runtime error: The application has corrupted its heap memory area (address zero)!
exception thrown: RuntimeError: abort(Runtime error: The application has corrupted its heap memory area (address zero)!) at Error
    at jsStackTrace (/Users/mbovel/emsdk/gettime.js:1942:17)
    at stackTrace (/Users/mbovel/emsdk/gettime.js:1959:16)
    at abort (/Users/mbovel/emsdk/gettime.js:1693:44)
    at checkStackCookie (/Users/mbovel/emsdk/gettime.js:1401:46)
    at exitRuntime (/Users/mbovel/emsdk/gettime.js:1488:3)
    at exit (/Users/mbovel/emsdk/gettime.js:2550:5)
    at callMain (/Users/mbovel/emsdk/gettime.js:2451:7)
    at doRun (/Users/mbovel/emsdk/gettime.js:2507:23)
    at run (/Users/mbovel/emsdk/gettime.js:2522:5)
    at runCaller (/Users/mbovel/emsdk/gettime.js:2424:19),RuntimeError: abort(Runtime error: The application has corrupted its heap memory area (address zero)!) at Error
    at jsStackTrace (/Users/mbovel/emsdk/gettime.js:1942:17)
    at stackTrace (/Users/mbovel/emsdk/gettime.js:1959:16)
    at abort (/Users/mbovel/emsdk/gettime.js:1693:44)
    at checkStackCookie (/Users/mbovel/emsdk/gettime.js:1401:46)
    at exitRuntime (/Users/mbovel/emsdk/gettime.js:1488:3)
    at exit (/Users/mbovel/emsdk/gettime.js:2550:5)
    at callMain (/Users/mbovel/emsdk/gettime.js:2451:7)
    at doRun (/Users/mbovel/emsdk/gettime.js:2507:23)
    at run (/Users/mbovel/emsdk/gettime.js:2522:5)
    at runCaller (/Users/mbovel/emsdk/gettime.js:2424:19)
    at abort (/Users/mbovel/emsdk/gettime.js:1699:9)
    at checkStackCookie (/Users/mbovel/emsdk/gettime.js:1401:46)
    at exitRuntime (/Users/mbovel/emsdk/gettime.js:1488:3)
    at exit (/Users/mbovel/emsdk/gettime.js:2550:5)
    at callMain (/Users/mbovel/emsdk/gettime.js:2451:7)
    at doRun (/Users/mbovel/emsdk/gettime.js:2507:23)
    at run (/Users/mbovel/emsdk/gettime.js:2522:5)
    at runCaller (/Users/mbovel/emsdk/gettime.js:2424:19)
    at removeRunDependency (/Users/mbovel/emsdk/gettime.js:1671:7)
    at receiveInstance (/Users/mbovel/emsdk/gettime.js:1833:5)

~/emsdk 
> emcc -s EXIT_RUNTIME=1 -o gettime.js gettime.c

~/emsdk 
> node gettime.js
438000
```

</p>
</details>

**Comment by kripken** [comment]
@mbovel I think you're missing the emcc flag `-s WASM_BIGINT`, I don't see it there?

**Comment by mbovel** [comment]
>  I think you're missing the emcc flag -s WASM_BIGINT, I don't see it there?

Oh, indeed, sorry. Now it works perfectly.

Thanks again!
