### ISSUE TITLE
v1.40.1 build error using the emscripten-supplied python3 6 views Subscribe 

### ISSUE THREAD

**Issue by ericmandel** [emscripten-core/emsdk#588]
[Originally reported here: https://groups.google.com/g/emscripten-discuss/c/GClN82zPXUk]

After updating to v1.40.1 from v1.39.19, I get the error shown below when using the emscripten-supplied version of python3. Utilizing my own previously installed version of python3 (which has 'requests' installed) works fine.

Running 'emcc --clear-ports', as suggested, did not help in this case.

````
system_libs:INFO: retrieving port: bzip2 from https://github.com/emscripten-ports/bzip2/archive/1.0.6.zip
system_libs:ERROR: a problem occurred when using an emscripten-ports library.  try to run `emcc --clear-ports` and then run this command again
Traceback (most recent call last):
  File "/Users/eric/emsdk/upstream/emscripten/tools/system_libs.py", line 1891, in retrieve
    import requests
ModuleNotFoundError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eric/emsdk/python/3.7.4_64bit/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Users/eric/emsdk/python/3.7.4_64bit/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/eric/emsdk/python/3.7.4_64bit/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/eric/emsdk/python/3.7.4_64bit/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/eric/emsdk/python/3.7.4_64bit/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Users/eric/emsdk/python/3.7.4_64bit/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/Users/eric/emsdk/python/3.7.4_64bit/lib/python3.7/http/client.py", line 1414, in connect
    server_hostname=server_hostname)
  File "/Users/eric/emsdk/python/3.7.4_64bit/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/Users/eric/emsdk/python/3.7.4_64bit/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/Users/eric/emsdk/python/3.7.4_64bit/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
````

**Comment by ericmandel** [comment]
From the original emscripten-discuss:

> Can you try running this command from the emsdk directory and see if if fixes these issue:
> 
> $ python/3.7.4_64bit/bin/python3 ./python/3.7.4_64bit/bin/pip3 install certifi

Installing certifi did not fix my problem, but installing requests did:

````
python/3.7.4_64bit/bin/python3 ./python/3.7.4_64bit/bin/pip3 install requests

````

**Comment by sbc100** [comment]
Thanks @ericmandel, I looked into a few options for how to fix this.. and I think you are right that installing the requests module is probably the cleanest solution.

It will involve updating the version of python for macOS that we bundle.

**Comment by ericmandel** [comment]
@sbc100 to be clear: I don't enough about Python to offer a solution with any confidence, I was just combining (the failure of) your initial suggestion with this suggestive error message:
````
ModuleNotFoundError: No module named 'requests'
````
