### ISSUE TITLE
emsdk install latest fails with "UnicodeDecodeError"

### ISSUE THREAD

**Issue by Squareys** [emscripten-core/emsdk#639]
Hi all,

This happens when using latests [master of emsdk (107dc62dd7fa90324d01658e6bcb514eca02d00a)](107dc62dd7fa90324d01658e6bcb514eca02d00a):

```
> emsdk update-tags
> emsdk install latest
Installing SDK 'sdk-releases-upstream-4ba921c8c8fe2e8cae071ca9889d5c27f5debd87-64bit'..
Skipped installing node-12.18.1-64bit, already installed.
Skipped installing python-3.7.4-pywin32-64bit, already installed.
Skipped installing java-8.152-64bit, already installed.
Installing tool 'releases-upstream-4ba921c8c8fe2e8cae071ca9889d5c27f5debd87-64bit'..
Downloading: D:/GitHub/emsdk/zips/4ba921c8c8fe2e8cae071ca9889d5c27f5debd87-wasm-binaries.zip from https://storage.googleapis.com/webassembly/emscripten-releases-builds/win/4ba921c8c8fe2e8cae071ca9889d5c27f5debd87/wasm-binaries.zip, 412055275 Bytes
Unpacking 'D:/GitHub/emsdk/zips/4ba921c8c8fe2e8cae071ca9889d5c27f5debd87-wasm-binaries.zip' to 'D:/GitHub/emsdk/upstream'
Done installing tool 'releases-upstream-4ba921c8c8fe2e8cae071ca9889d5c27f5debd87-64bit'.
Running post-install step: npm ci ...
Running post-install step: npm install google-closure-compiler-windows
Traceback (most recent call last):
  File "D:\GitHub\emsdk\\emsdk.py", line 3050, in <module>
    sys.exit(main())
  File "D:\GitHub\emsdk\\emsdk.py", line 3030, in main
    success = tool.install()
  File "D:\GitHub\emsdk\\emsdk.py", line 1818, in install
    return self.install_sdk()
  File "D:\GitHub\emsdk\\emsdk.py", line 1835, in install_sdk
    success = emscripten_npm_install(self, os.path.join(emsdk_path(), install_path, 'emscripten'))
  File "D:\GitHub\emsdk\\emsdk.py", line 1256, in emscripten_npm_install
    universal_newlines=True)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 395, in check_output
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 474, in run
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 926, in communicate
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 617: character maps to <undefined>
```

Both on Git Bash and Windows CMD.

Best,
Jonathan

**Comment by Squareys** [comment]
I tried checking out `2.0.4` of emsdk, but that did not fix the issue.
Setting `chcp 65001` as described in [this stackoverflow](https://stackoverflow.com/questions/49150550/python-subprocess-encoding) fixed the issue for me.

**Comment by sbc100** [comment]
Do you have PYTHONHOME set?  Can you try unsetting it?

The path `D:\obj\windows-release\37amd64_Release` makes me think somehow the wrong python libraryes are being used, but we have code in emsdk.bat that is supposed to unset PYTHONHOME and make this work.

**Comment by elo-siema** [comment]
> 
> 
> I tried checking out `2.0.4` of emsdk, but that did not fix the issue.
> Setting `chcp 65001` as described in [this stackoverflow](https://stackoverflow.com/questions/49150550/python-subprocess-encoding) fixed the issue for me.

Would you mind sharing the modified file? I can't quite figure out where to make this change.

**Comment by Squareys** [comment]
@elo-siema You can run that command before running `emsdk`, I didn't modify the code

**Comment by fesieg** [comment]
@Squareys which command, I can't seem to figure it out

**Comment by Squareys** [comment]
@fesieg You just type `chcp 65001` in a terminal before running emsdk 😅

**Comment by sbc100** [comment]
I think this issue comes from using the wrong python libraries.  The `37amd64_Release\msi_python\` paths in the error message make it looks like maybe `PYTHONHOME` is set when here?

**Comment by auermich93** [comment]
Invoking `chcp 65001` in cmd.exe (not powershell) resolved the issue for me.
