### ISSUE TITLE
Garbage

### ISSUE THREAD

**Issue by adimetrius** [emscripten-core/emsdk#673]
Downloaded and installed following the instructions for Linux. SDK from git, then activate latest, source emsdk_env.sh.

Then did

./emcc tests/hello_world.c
bash: ./emcc: No such file or directory

Found the emcc script in upstream/emscripten, ran
./emcc hello_world.c

Traceback (most recent call last):
  File "/home/antonio/dev/emsdk/upstream/emscripten/emcc.py", line 40, in <module>
    import emscripten
  File "/home/antonio/dev/emsdk/upstream/emscripten/emscripten.py", line 463
    args.append(f'--separate-data-segments={memfile}')
                                                    ^
SyntaxError: invalid syntax

rukozhopi!

**Comment by sbc100** [comment]
The `./` as the beginning on emcc should not be used when trying to run emcc from your PATH.   If you use emsdk you should just run `emcc` without the `./` since emcc is not in that current working directory.

The second issue you have looks like you are missing a version of python that supports f-strings.   Emscripten requires python3.6 or above.
