### ISSUE TITLE
No sound and "Uncaught ReferenceError: dynCall is not defined" error from SDL2 applications

### ISSUE THREAD

**Issue by Wohlstand** [emscripten-core/emsdk#678]
Recently I built the game with the latest SDK at the moment I writing this issue:
```
releases-upstream-4764c5c323a474f7ba28ae991b0c9024fccca43c-64bit
```

From my game that I built with this SDK, I getting the next error:
```
Uncaught ReferenceError: dynCall is not defined
```
The game itself works, but no sound, and the persistent spamming of the console with such error.

The game build itself: https://wohlsoft.ru/TheXTech/aod-on-web/
It worked perfectly with an older SDK I had.

No matter where I built the game: my local machine, or CI server, the result is the same.

**Comment by sbc100** [comment]
Are you using `dynCall` in your application JS code?

This functions was converted into a library function in #12002 which means that you need to add an explicit dependency on it.   If the code that depends on it is part of a JS library you can use the depencency system. e.g. `myFunc__deps: ['$dynCall']`.    If the code that depends on it is part of EM_ASM/EM_JS or pre-js/post-js then you can add the dependency on the command line by adding this function to `-s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE`. 

Apologies for this breakage, we should have given more consideration to external users of this API when we made this transition.

**Comment by Wohlstand** [comment]
I don't use this function directly, probably SDL2 does use it, lemme check their repo...

**Comment by Wohlstand** [comment]
Okay, I did the check, SDL2 does use this call inside of self:
```
vitaly@whl-pc-001l:~/_git_repos/SDL$ grep -re "dynCall" src
src/audio/emscripten/SDL_emscriptenaudio.c:                    dynCall('vi', $2, [$3]);
src/audio/emscripten/SDL_emscriptenaudio.c:                dynCall('vi', $2, [$3]);
src/audio/emscripten/SDL_emscriptenaudio.c:                dynCall('vi', $2, [$3]);
```
3 times at here:
https://hg.libsdl.org/SDL/file/4cab0e41f54d/src/audio/emscripten/SDL_emscriptenaudio.c#l278
Should I notice SDL2 developers about this thing? (@sezero, please look!) or every project that uses SDL2 should specify the `-s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE` flag?

**Comment by sbc100** [comment]
Hmm.. it looks like this is supposed to be taken care of by: https://github.com/emscripten-core/emscripten/blob/51cb3ab312e885fa97fecea36fabfe3b4f330280/tools/ports/sdl2.py#L93

**Comment by Wohlstand** [comment]
At me, I do my own build of SDL2, so, seems I should define such flags by myself.

**Comment by sbc100** [comment]
Ah I see, you don't use the port?   In that case yes, you should add those flags.

**Comment by Wohlstand** [comment]
Okay, my attempts were causing next:
```cmake
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -s ASYNCIFY=1 -s \"DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=['\$autoResumeAudioContext', '\$dynCall']\"")
```

error:
```
warning: undefined symbol:  (referenced by top-level compiled C/C++ code)
Internal compiler error in src/compiler.js!
Please create a bug report at https://github.com/emscripten-core/emscripten/issues/
with a log of the build and the input files used to run. Exception message: "TypeError: Cannot read property '0' of undefined" | TypeError: Cannot read property '0' of undefined
    at isJsOnlyIdentifier (eval at load (/home/vitaly/Qt/Tools/emsdk/upstream/emscripten/src/compiler.js:38:8), <anonymous>:46:15)
    at addFromLibrary (eval at load (/home/vitaly/Qt/Tools/emsdk/upstream/emscripten/src/compiler.js:38:8), <anonymous>:234:14)
    at functionStubHandler (eval at load (/home/vitaly/Qt/Tools/emsdk/upstream/emscripten/src/compiler.js:38:8), <anonymous>:336:15)
    at Array.forEach (<anonymous>)
    at JSify (eval at load (/home/vitaly/Qt/Tools/emsdk/upstream/emscripten/src/compiler.js:38:8), <anonymous>:449:24)
    at Object.<anonymous> (/home/vitaly/Qt/Tools/emsdk/upstream/emscripten/src/compiler.js:98:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
em++: error: '/home/vitaly/Qt/Tools/emsdk/node/12.18.1_64bit/bin/node /home/vitaly/Qt/Tools/emsdk/upstream/emscripten/src/compiler.js /tmp/tmpwyh6ydix.txt' failed (1)
ninja: build stopped: subcommand failed.
```

I tried to specify `_autoResumeAudioContext` and `_dynCall`, and just `autoResumeAudioContext` and `dynCall`, I getting "undefined reference" on them.

**Comment by sbc100** [comment]
Can you see the link command the cmake uses?  (If you use `ninja` it will show the failing command by default, if your `make` I think you need to run make with `VERBOSE=1`)

**Comment by Wohlstand** [comment]
When I call with the plain names:
```
error: undefined symbol: autoResumeAudioContext (referenced by top-level compiled C/C++ code)
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _autoResumeAudioContext may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: dynCall (referenced by top-level compiled C/C++ code)
warning: _dynCall may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
em++: error: '/home/vitaly/Qt/Tools/emsdk/node/12.18.1_64bit/bin/node /home/vitaly/Qt/Tools/emsdk/upstream/emscripten/src/compiler.js /tmp/tmpwdvzep55.txt' failed (1)
ninja: build stopped: subcommand failed.
```

When I call with "$"-begin:
```
error: undefined symbol:  (referenced by top-level compiled C/C++ code)
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _ may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Internal compiler error in src/compiler.js!
Please create a bug report at https://github.com/emscripten-core/emscripten/issues/
with a log of the build and the input files used to run. Exception message: "TypeError: Cannot read property '0' of undefined" | TypeError: Cannot read property '0' of undefined
    at isJsOnlyIdentifier (eval at load (/home/vitaly/Qt/Tools/emsdk/upstream/emscripten/src/compiler.js:38:8), <anonymous>:46:15)
    at addFromLibrary (eval at load (/home/vitaly/Qt/Tools/emsdk/upstream/emscripten/src/compiler.js:38:8), <anonymous>:234:14)
    at functionStubHandler (eval at load (/home/vitaly/Qt/Tools/emsdk/upstream/emscripten/src/compiler.js:38:8), <anonymous>:336:15)
    at Array.forEach (<anonymous>)
    at JSify (eval at load (/home/vitaly/Qt/Tools/emsdk/upstream/emscripten/src/compiler.js:38:8), <anonymous>:449:24)
    at Object.<anonymous> (/home/vitaly/Qt/Tools/emsdk/upstream/emscripten/src/compiler.js:98:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
em++: error: '/home/vitaly/Qt/Tools/emsdk/node/12.18.1_64bit/bin/node /home/vitaly/Qt/Tools/emsdk/upstream/emscripten/src/compiler.js /tmp/tmpyaft5gmv.txt' failed (1)
ninja: build stopped: subcommand failed.
```

**Comment by Wohlstand** [comment]
bad that content of `/tmp/tmpyaft5gmv.txt` is missing, the file got deleted immediately...

**Comment by Wohlstand** [comment]
And with `_` prefix:
```
error: undefined symbol: _autoResumeAudioContext (referenced by top-level compiled C/C++ code)
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: __autoResumeAudioContext may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _dynCall (referenced by top-level compiled C/C++ code)
warning: __dynCall may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
em++: error: '/home/vitaly/Qt/Tools/emsdk/node/12.18.1_64bit/bin/node /home/vitaly/Qt/Tools/emsdk/upstream/emscripten/src/compiler.js /tmp/tmpkrkcmdon.txt' failed (1)
ninja: build stopped: subcommand failed.
```

**Comment by Wohlstand** [comment]
Okay, I found the solution:
```cmake
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -s \"DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=['\\$autoResumeAudioContext', '\\$dynCall']\"")
```
I had to escape by double-slash: `"\\$"` to make sure Bash will receive the `\$`, and that works :fox_face:

**Comment by Wohlstand** [comment]
So, the problem has been resolved! Thanks for tips and notes, @sbc100 ! :fox_face:
