### ISSUE TITLE
Windows Build Fails

### ISSUE THREAD

**Issue by gerald-dotcom** [emscripten-core/emsdk#685]
I have a `.bat` file and it execute following commands,

```
call C:/emsdk/emsdk activate latest
call C:/emsdk/emsdk_env.bat

cd ./build
call emcmake ..
```

In past it worked but newer versions of Emscripten seems running into issues lately. 

Here is Stacktrace 

```
Traceback (most recent call last):
  File "C:\emsdk\upstream\emscripten\\emcmake.py", line 33, in <module>
    sys.exit(run())
  File "C:\emsdk\upstream\emscripten\\emcmake.py", line 26, in run
    building.configure(sys.argv[1:])
  File "C:\emsdk\upstream\emscripten\tools\building.py", line 339, in configure
    run_process(args, stdout=stdout, stderr=stderr, env=env, **kwargs)
  File "C:\emsdk\upstream\emscripten\tools\shared.py", line 98, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 472, in run
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 775, in __init__
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 1178, in _execute_child
PermissionError: [WinError 5] Access is denied
```

I ran `python -c "import subprocess; subprocess.call(['cmake'])"` and it finds CMake and then I hooked  `run_process `function in `shared.py` as follows,

```
  print(cmd)
  print(args)
```

These two commands logs,

```
['..']
()
```

**Comment by sbc100** [comment]
The command line for emcmake expects to you to pass cmake as the first argument:

```
 $ ./emcmake --help
emcmake is a helper for cmake, setting various environment
variables so that emcc etc. are used. Typical usage:

  emcmake cmake [FLAGS]

```
