### ISSUE TITLE
broken emrun in 2.0.14

### ISSUE THREAD

**Issue by 3d4m-vladimir** [emscripten-core/emsdk#712]
Running with:
`emrun --no_browser --hostname 0.0.0.0 tests/cmake/out/app.html`

```
Exception happened during processing of request from ('____ip_____', 42968)
17	Traceback (most recent call last):
18	  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
19	    self.finish_request(request, client_address)
20	  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
21	    self.RequestHandlerClass(request, client_address, self)
22	  File "/usr/lib/python3.7/http/server.py", line 646, in __init__
23	    super().__init__(*args, **kwargs)
24	  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
25	    self.handle()
26	  File "/usr/lib/python3.7/http/server.py", line 426, in handle
27	    self.handle_one_request()
28	  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
29	    method()
30	  File "/usr/lib/python3.7/http/server.py", line 650, in do_GET
31	    f = self.send_head()
32	  File "/emsdk/upstream/emscripten/emrun.py", line 591, in send_head
33	    detect_browser_processes()
34	  File "/emsdk/upstream/emscripten/emrun.py", line 429, in detect_browser_processes
35	    running_browser_processes = list_processes_by_name(browser_exe)
36	  File "/emsdk/upstream/emscripten/emrun.py", line 1420, in list_processes_by_name
37	    logv('Searching for processes by full path name "' + exe_full_path + '".. found ' + str(len(pids)) + ' entries')
38	TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by sbc100** [comment]
Looks like it must have been https://github.com/emscripten-core/emscripten/pull/12034.

@juj could you take a look?

**Comment by juj** [comment]
Apologies for the regression. I believe a fix for this exists in this PR: https://github.com/emscripten-core/emscripten/pull/13412 , on this line: https://github.com/emscripten-core/emscripten/pull/13412/files#diff-dc0b4ef45b945dfeb75f7462aacf00470588c37739844b995ba7ecf4c895bd78R435

If you locally apply that, does that resolve the issue?

**Comment by 3d4m-vladimir** [comment]
Issue had been discovered on internal CI system where we use docker container (CI switched to 2.0.13 ). Unfortunately no easy way to test with reverted changes in emrun.

**Comment by seveirbian** [comment]
I met the same error. I take the following method: 
Modifying this line of code in "/root/emsdk/upstream/emscripten/emrun.py" file at line 1420 logv('Searching for processes by full path name "' + exe_full_path + '".. found ' + str(len(pids)) + ' entries') to logv('Searching for processes by full path name "' + str(exe_full_path) + '".. found ' + str(len(pids)) + ' entries')
 After the above modification, my hello world webassembly code runs correctly.
