### ISSUE TITLE
error in acorn-optimizer when building Wacl

### ISSUE THREAD

**Issue by sandeep-gh** [emscripten-core/emsdk#716]
Wacl is TCL port for Webassembly. The build fails at final step when running acorn-optimizer. Have attached the full error:
```
emcc --pre-js preGeneratedJs.js --post-js js/postJsRequire.js -Oz -s WASM=1 -s FORCE_FILESYSTEM=1 -s RESERVED_FUNCTION_POINTERS=100 --memory-init-file 0  --llvm-lto 3 --closure 0 -s EXPORTED_FUNCTIONS="[ '_main', '_Wacl_GetInterp', '_Tcl_Eval', '_Tcl_GetStringResult' ]" jsbuild/lib/libtcl8.6.a jsbuild/lib/tdom0.8.3/libtdom0.8.3.a jsbuild/lib/rl_json0.9.7/librl_json0.9.7.a -o wacl.js
emcc:WARNING: --llvm-lto ignored when using llvm backend
/media/kabira/home/opensourceforgery/emscripten/emsdk/emscripten/master/tools/acorn-optimizer.js:1433
  throw err;
  ^

SyntaxError: Unexpected token (128:2)
  Module.expectedDataFileDownloads++;
  ^

    at Parser.pp$4.raise (/media/kabira/home/opensourceforgery/emscripten/emsdk/emscripten/master/node_modules/acorn/dist/acorn.js:2927:15)
    at Parser.pp.unexpected (/media/kabira/home/opensourceforgery/emscripten/emsdk/emscripten/master/node_modules/acorn/dist/acorn.js:698:10)
    at Parser.pp.expect (/media/kabira/home/opensourceforgery/emscripten/emsdk/emscripten/master/node_modules/acorn/dist/acorn.js:692:28)
    at Parser.pp$3.parseExprList (/media/kabira/home/opensourceforgery/emscripten/emsdk/emscripten/master/node_modules/acorn/dist/acorn.js:2818:14)
    at Parser.pp$3.parseSubscript (/media/kabira/home/opensourceforgery/emscripten/emsdk/emscripten/master/node_modules/acorn/dist/acorn.js:2184:27)
    at Parser.pp$3.parseSubscripts (/media/kabira/home/opensourceforgery/emscripten/emsdk/emscripten/master/node_modules/acorn/dist/acorn.js:2147:26)
    at Parser.pp$3.parseExprSubscripts (/media/kabira/home/opensourceforgery/emscripten/emsdk/emscripten/master/node_modules/acorn/dist/acorn.js:2132:23)
    at Parser.pp$3.parseMaybeUnary (/media/kabira/home/opensourceforgery/emscripten/emsdk/emscripten/master/node_modules/acorn/dist/acorn.js:2106:19)
    at Parser.pp$3.parseExprOps (/media/kabira/home/opensourceforgery/emscripten/emsdk/emscripten/master/node_modules/acorn/dist/acorn.js:2041:21)
    at Parser.pp$3.parseMaybeConditional (/media/kabira/home/opensourceforgery/emscripten/emsdk/emscripten/master/node_modules/acorn/dist/acorn.js:2024:21) {
  pos: 4415,
  loc: Position { line: 128, column: 2 },
  raisedAt: 4421
}
emcc: error: '/media/kabira/home/opensourceforgery/emscripten/emsdk/node/12.18.1_64bit/bin/node /media/kabira/home/opensourceforgery/emscripten/emsdk/emscripten/master/tools/acorn-optimizer.js /tmp/emscripten_temp_vlkuxarb/wacl.js.pp.js AJSDCE minifyWhitespace' failed (1)
```
Not sure if this is Wacl  configure/make bug or something on emscripten side.

**Comment by kripken** [comment]
There might be something bad right before the `Module.expectedDataFileDownloads++;` it mentions (that makes it expect something else after it). If you build with `EMCC_DEBUG=1` in the env to save temp files, you can get that file and test running the optimizer command on it directly.

**Comment by sandeep-gh** [comment]
I am able to run the optimizer in standalone.  I am not familiar with Javascript  so not able to pick what wrong with the syntax. The optimizer doesn't like the Module keyword which is defined as follows:
```javascript
 var Module = typeof Module !== 'undefined' ? Module : {};
```
Some context around the line where the error occurs:
```javascript
define('tcl/wacl', function () {
...
...
..
}
 Module.expectedDataFileDownloads++;
(function() {
...
...
}
```

**Comment by kripken** [comment]
It's hard to say what's wrong without the full file, I'm afraid. If you can't provide it, though, then where does `define(..` from from, and where does the `(function()..` come from?

(At least the former doesn't look like something from emscripten, so maybe the problem is external code being added. It may require very new JS syntax for example, newer than the emscripten optimizer can handle, is one possibility.)

**Comment by sandeep-gh** [comment]
Have attached the wacl file. I am not sure about where the `define(..)` comes from. Will look around to track that. 

[wacl.js.pp.js.zip](https://github.com/emscripten-core/emsdk/files/6028823/wacl.js.pp.js.zip)

**Comment by kripken** [comment]
That does look like invalid JS. Running `node` on it gives a similar error. Is it possible the bad code arrives from a `--pre-js` or `--post-js`?
