### ISSUE TITLE
emcc warning emscipten a long time

### ISSUE THREAD

**Issue by Crusoekid** [emscripten-core/emsdk#779]
I clone the git code and use 'emsdk install latest && emsdk activate latest && ./emsdk_env.sh'

when i use the sample 'hello'.

see this, and i wate one day has no result. why??

cache:WARNING: Accessing the Emscripten cache at "/home/openailab/workspace/workspace/wasm/emsdk/upstream/emscripten/cache" is taking a long time, another process should be writing to it. If there are none and you suspect this process has deadlocked, try deleting the lock file "/home/openailab/workspace/workspace/wasm/emsdk/upstream/emscripten/cache/cache.lock" and try again. If this occurs deterministically, consider filing a bug.

i use comm 'emcc hello.c -s WASM=1 -o hello.html'

my system is ubuntu 18.04

**Comment by sbc100** [comment]
Interesting, that really should not happen.    Do you see anything else in the output.   Normally I would expect the cache access to be proceeded by a messaging about that its about to generate.

Also, did you try remove the `.lock` file as a suggested in the error message?

**Comment by Crusoekid** [comment]
no anything else in the output.  

Yes.i delete the .lock, but i doesn`t work.

**Comment by Crusoekid** [comment]
when i use version 2.0.10 ,it show share:INFO:(Emscriten : Runnning sanity checks),but  it also can`t emcc sucess.
show long time that error

**Comment by Crusoekid** [comment]
Traceback (most recent call last):
  File "/home/openailab/workspace/workspace/wasm/emsdk/fastcomp/emscripten/emcc", line 11, in <module>
    python_selector.run(__file__)
  File "/home/openailab/workspace/workspace/wasm/emsdk/fastcomp/emscripten/tools/python_selector.py", line 24, in run
    sys.exit(subprocess.call([python, os.path.realpath(filename) + '.py'] + sys.argv[1:]))
  File "/usr/lib/python3.6/subprocess.py", line 289, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1477, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.6/subprocess.py", line 1424, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)

**Comment by sbc100** [comment]
What is `emsdk/fastcomp` showing up in that backtrace?   fastcomp versions of the SDK are only available for very old versions.      Unless you are explicitly wanting to use fastcomp I would completely remove `emsdk/fastcomp` directory (and investigate why its in your PATH).

**Comment by Crusoekid** [comment]
i use clone to download emsdk,i don`t know why have emsdk/fastcomp

**Comment by sbc100** [comment]
Closing out old issues.   Feel free to re-open if this is still effecting you.
