### ISSUE TITLE
Failed to compile libharfbuzz on Arch Linux

### ISSUE THREAD

**Issue by albertvaka** [emscripten-core/emsdk#796]
I'm trying to compile a project that depends on `SDL_TTF` which in turn depends on `harfbuzz`, but it's failing to build with this error (which doesn't make a lot of sense, since the compiler is in place but it still complains it can't find it... and actually it manged to build everything else before harfbuzz). This is on a fresh emsdk install on Arch Linux. The exact same code compiles fine with a fresh emscripten install on my Mac 10.14.

```
cache:INFO: generating port: sysroot/lib/wasm32-emscripten/libharfbuzz.a... (this will be cached in "/home/vaka/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libharfbuzz.a" for subsequent builds)
root:INFO: building port: harfbuzz
configure: cmake -B/home/vaka/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz -H/home/vaka/emsdk/upstream/emscripten/cache/ports/harfbuzz/harfbuzz-1.7.5 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/vaka/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz -DFREETYPE_INCLUDE_DIRS=/home/vaka/emsdk/upstream/emscripten/cache/sysroot/include/freetype2/freetype;/home/vaka/emsdk/upstream/emscripten/cache/sysroot/include/freetype2/freetype/config -DFREETYPE_LIBRARY=/home/vaka/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libfreetype.a -DHB_HAVE_FREETYPE=ON -DCMAKE_TOOLCHAIN_FILE=/home/vaka/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR="/home/vaka/emsdk/node/14.15.5_64bit/bin/node"
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Looking for atexit
-- Looking for atexit - not found
-- Looking for mprotect
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error at /usr/share/cmake-3.20/Modules/CheckFunctionExists.cmake:92 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  CMakeLists.txt:99 (check_function_exists)
  CMakeLists.txt:105 (check_funcs)


-- Configuring incomplete, errors occurred!
See also "/home/vaka/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/CMakeFiles/CMakeError.log".
emcmake: error: 'cmake -B/home/vaka/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz -H/home/vaka/emsdk/upstream/emscripten/cache/ports/harfbuzz/harfbuzz-1.7.5 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/vaka/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz -DFREETYPE_INCLUDE_DIRS=/home/vaka/emsdk/upstream/emscripten/cache/sysroot/include/freetype2/freetype;/home/vaka/emsdk/upstream/emscripten/cache/sysroot/include/freetype2/freetype/config -DFREETYPE_LIBRARY=/home/vaka/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libfreetype.a -DHB_HAVE_FREETYPE=ON -DCMAKE_TOOLCHAIN_FILE=/home/vaka/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR="/home/vaka/emsdk/node/14.15.5_64bit/bin/node"' failed (1)
Traceback (most recent call last):
  File "/home/vaka/emsdk/upstream/emscripten/em++.py", line 14, in <module>
    sys.exit(emcc.run(sys.argv))
  File "/home/vaka/emsdk/upstream/emscripten/emcc.py", line 2179, in run
    compile_source_file(i, input_file)
  File "/home/vaka/emsdk/upstream/emscripten/emcc.py", line 2167, in compile_source_file
    cmd = get_clang_command(input_file)
  File "/home/vaka/emsdk/upstream/emscripten/emcc.py", line 2117, in get_clang_command
    return get_compiler(use_cxx(src_file)) + get_cflags(options, args) + compile_args + [src_file]
  File "/home/vaka/emsdk/upstream/emscripten/emcc.py", line 802, in get_cflags
    system_libs.add_ports_cflags(cflags, shared.Settings)
  File "/home/vaka/emsdk/upstream/emscripten/tools/system_libs.py", line 1890, in add_ports_cflags
    port.get(Ports, settings, shared)
  File "/home/vaka/emsdk/upstream/emscripten/tools/ports/harfbuzz.py", line 70, in get
    return [shared.Cache.get_lib(get_lib_name(settings), create, what='port')]
  File "/home/vaka/emsdk/upstream/emscripten/tools/cache.py", line 130, in get_lib
    return self.get(name, *args, **kwargs)
  File "/home/vaka/emsdk/upstream/emscripten/tools/cache.py", line 158, in get
    creator(cachename)
  File "/home/vaka/emsdk/upstream/emscripten/tools/ports/harfbuzz.py", line 63, in create
    shared.run_process(cmake_cmd)
  File "/home/vaka/emsdk/upstream/emscripten/tools/shared.py", line 96, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/vaka/emsdk/upstream/emscripten/emcmake', 'cmake', '-B/home/vaka/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz', '-H/home/vaka/emsdk/upstream/emscripten/cache/ports/harfbuzz/harfbuzz-1.7.5', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/home/vaka/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz', '-DFREETYPE_INCLUDE_DIRS=/home/vaka/emsdk/upstream/emscripten/cache/sysroot/include/freetype2/freetype;/home/vaka/emsdk/upstream/emscripten/cache/sysroot/include/freetype2/freetype/config', '-DFREETYPE_LIBRARY=/home/vaka/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libfreetype.a', '-DHB_HAVE_FREETYPE=ON']' returned non-zero exit status 1.
```

**Comment by sbc100** [comment]
What is in the error log that it points you too: `See also "/home/vaka/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/CMakeFiles/CMakeError.log".`?

I wonder if that cmake version warning is related.  The version of cmake I have installed is 3.18.4 and I confirmed it builds fine for me.

**Comment by albertvaka** [comment]
Contents of `CMakeError.log`:

```
Determining if the function atexit exists failed with the following output:
Change Dir: /home/vaka/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_34fb7/fast && make[1]: Entering directory '/home/vaka/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/CMakeFiles/CMakeTmp'
/usr/bin/make  -f CMakeFiles/cmTC_34fb7.dir/build.make CMakeFiles/cmTC_34fb7.dir/build
make[2]: Entering directory '/home/vaka/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_34fb7.dir/CheckFunctionExists.c.o
/home/vaka/emsdk/upstream/emscripten/emcc   -pipe -I./engine  -I vendor/SDL_gpu/include  -I vendor/stb_image  -I vendor/imgui_impl  -I vendor/imgui  -I vendor/magic_enum -Wall -Wno-unused-parameter  -D_DEBUG -g -D_IMGUI -O0 -s EXPORTED_FUNCTIONS='["_main", "_start_main_loop"]' -s EXPORTED_RUNTIME_METHODS='["ccall"]' -Oz -DSDL_GPU_DISABLE_OPENGL -DSDL_GPU_DISABLE_GLES_1 -s USE_SDL_TTF=2 -s USE_SDL_MIXER=2 -s USE_OGG -s USE_VORBIS -s ALLOW_MEMORY_GROWTH=1 --preload-file bin/data@/data --use-preload-plugins -s MIN_WEBGL_VERSION=2 -s MAX_WEBGL_VERSION=2 -DSDL_GPU_DISABLE_GLES_2 -DIMGUI_IMPL_OPENGL_ES3 -DCHECK_FUNCTION_EXISTS=atexit -MD -MT CMakeFiles/cmTC_34fb7.dir/CheckFunctionExists.c.o -MF CMakeFiles/cmTC_34fb7.dir/CheckFunctionExists.c.o.d -o CMakeFiles/cmTC_34fb7.dir/CheckFunctionExists.c.o -c /usr/share/cmake-3.20/Modules/CheckFunctionExists.c
cache:INFO: generating port: sysroot/lib/wasm32-emscripten/libharfbuzz.a... (this will be cached in "/home/vaka/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libharfbuzz.a" for subsequent builds)
root:INFO: building port: harfbuzz
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
configure: cmake -B/home/vaka/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz -H/home/vaka/emsdk/upstream/emscripten/cache/ports/harfbuzz/harfbuzz-1.7.5 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/vaka/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz -DFREETYPE_INCLUDE_DIRS=/home/vaka/emsdk/upstream/emscripten/cache/sysroot/include/freetype2/freetype;/home/vaka/emsdk/upstream/emscripten/cache/sysroot/include/freetype2/freetype/config -DFREETYPE_LIBRARY=/home/vaka/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libfreetype.a -DHB_HAVE_FREETYPE=ON -DCMAKE_TOOLCHAIN_FILE=/home/vaka/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR="/home/vaka/emsdk/node/14.15.5_64bit/bin/node"
Current working directory cannot be established.
emcmake: error: 'cmake -B/home/vaka/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz -H/home/vaka/emsdk/upstream/emscripten/cache/ports/harfbuzz/harfbuzz-1.7.5 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/vaka/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz -DFREETYPE_INCLUDE_DIRS=/home/vaka/emsdk/upstream/emscripten/cache/sysroot/include/freetype2/freetype;/home/vaka/emsdk/upstream/emscripten/cache/sysroot/include/freetype2/freetype/config -DFREETYPE_LIBRARY=/home/vaka/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libfreetype.a -DHB_HAVE_FREETYPE=ON -DCMAKE_TOOLCHAIN_FILE=/home/vaka/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR="/home/vaka/emsdk/node/14.15.5_64bit/bin/node"' failed (1)
Traceback (most recent call last):
  File "/home/vaka/emsdk/upstream/emscripten/emcc.py", line 3475, in <module>
    sys.exit(main(sys.argv))
  File "/home/vaka/emsdk/upstream/emscripten/emcc.py", line 3468, in main
    ret = run(args)
  File "/home/vaka/emsdk/upstream/emscripten/emcc.py", line 2179, in run
    compile_source_file(i, input_file)
  File "/home/vaka/emsdk/upstream/emscripten/emcc.py", line 2167, in compile_source_file
    cmd = get_clang_command(input_file)
  File "/home/vaka/emsdk/upstream/emscripten/emcc.py", line 2117, in get_clang_command
    return get_compiler(use_cxx(src_file)) + get_cflags(options, args) + compile_args + [src_file]
  File "/home/vaka/emsdk/upstream/emscripten/emcc.py", line 802, in get_cflags
    system_libs.add_ports_cflags(cflags, shared.Settings)
  File "/home/vaka/emsdk/upstream/emscripten/tools/system_libs.py", line 1890, in add_ports_cflags
    port.get(Ports, settings, shared)
  File "/home/vaka/emsdk/upstream/emscripten/tools/ports/harfbuzz.py", line 70, in get
    return [shared.Cache.get_lib(get_lib_name(settings), create, what='port')]
  File "/home/vaka/emsdk/upstream/emscripten/tools/cache.py", line 130, in get_lib
    return self.get(name, *args, **kwargs)
  File "/home/vaka/emsdk/upstream/emscripten/tools/cache.py", line 158, in get
    creator(cachename)
  File "/home/vaka/emsdk/upstream/emscripten/tools/ports/harfbuzz.py", line 63, in create
    shared.run_process(cmake_cmd)
  File "/home/vaka/emsdk/upstream/emscripten/tools/shared.py", line 96, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/vaka/emsdk/upstream/emscripten/emcmake', 'cmake', '-B/home/vaka/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz', '-H/home/vaka/emsdk/upstream/emscripten/cache/ports/harfbuzz/harfbuzz-1.7.5', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/home/vaka/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz', '-DFREETYPE_INCLUDE_DIRS=/home/vaka/emsdk/upstream/emscripten/cache/sysroot/include/freetype2/freetype;/home/vaka/emsdk/upstream/emscripten/cache/sysroot/include/freetype2/freetype/config', '-DFREETYPE_LIBRARY=/home/vaka/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libfreetype.a', '-DHB_HAVE_FREETYPE=ON']' returned non-zero exit status 1.
make[2]: *** [CMakeFiles/cmTC_34fb7.dir/build.make:79: CMakeFiles/cmTC_34fb7.dir/CheckFunctionExists.c.o] Error 1
make[2]: Leaving directory '/home/vaka/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/CMakeFiles/CMakeTmp'
make[1]: *** [Makefile:127: cmTC_34fb7/fast] Error 2
make[1]: Leaving directory '/home/vaka/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/CMakeFiles/CMakeTmp'

```

**Comment by albertvaka** [comment]
On Arch (not working): `cmake version 3.20.1` 
On MacOS (working): `cmake version 3.19.6`

Let me update CMake on my Mac and see.

**Comment by sbc100** [comment]
A yes it looks like that problem is that your program's cflags (`-s USE_SDL_TTF=2 -s USE_SDL_MIXER=2 -s USE_OGG`) are leaking into the harfbuzz build.  This is causing the harfbuzz port to build built recursively).

Are are you specifying those flags?  Are you using some kind of environment variable?  We have a function which is supposed to create a clean environment for building ports: https://github.com/emscripten-core/emscripten/blob/0f5db283745698f5326d5e06d719357068f3e822/tools/system_libs.py#L70-L79

This was recently updated as part of #13760 so that could be the fix you need.  Are you using 2.0.16 (which contains that fix) or above?

**Comment by albertvaka** [comment]
You are right, my Makefile is adding those to the environment (as `CFLAGS`). What is weird, tough, is that on the system it works I'm using the exact same Makefile... I'm using version 2.0.17.

**Comment by albertvaka** [comment]
Inspired by the change you linked I submitted emscripten-core/emscripten#13995 which fixes this issue. The ideal solution, though, would be to clean the environment for all commands invoked when building ports, instead of doing it case by case.
