### ISSUE TITLE
"emconfigure configure" returns error when run on Windows 10

### ISSUE THREAD

**Issue by mrmessagewriter** [emscripten-core/emsdk#859]
``When trying to get libjpeg to build and compile as shown here [https://github.com/AntoineViau/webassembly-jpeg](AntoineViau WebAssembly)
This works fine on Linux, but I need it run on Windows.  However when running:  **emconfigure configure** from the command line, where "emcc" works just fine for compiling.   I get the following error:
`
configure: configure
Traceback (most recent call last):
  File "c:\root\emsdk\upstream\emscripten\\emconfigure.py", line 50, in <module>
    sys.exit(run())
  File "c:\root\emsdk\upstream\emscripten\\emconfigure.py", line 43, in run
    building.configure(sys.argv[1:])
  File "c:\root\emsdk\upstream\emscripten\tools\building.py", line 326, in configure
    run_process(args, stdout=stdout, stderr=stderr, env=env, **kwargs)
  File "c:\root\emsdk\upstream\emscripten\tools\shared.py", line 96, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "C:\Program Files\Python38\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python38\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python38\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified`

Anyone have any experience with this?  I updated to the latest emscripten, and still this is an issue.

**Comment by sbc100** [comment]
`emconfigure` doesn't generally work on windows because its a wrapper around `configure` which itself is a `bash` shell script, and bash is not generally available on windows.  You would need some kind of `bash` installation such as mingw or `cygwin` to make that work.

Perhaps we can find a way to show a better error message here?

**Comment by mrmessagewriter** [comment]
Hmm okay.  I guess perhaps the best choice for me is to then build on a Linux box somewhere, as part of the build.  I'll look into this, thanks!

As for a better error?  Yeah that could be significantly useful for many people, other then myself.

**Comment by sbc100** [comment]
If you just want libjpeg you can build with `-sUSE_LIBJPEG` since that is one of the ports that comes bundles with emscripten.

**Comment by hasufell** [comment]
Even under msys2 with bash, things are borked. It's breaking PATH.

Before:

```
/c/Users/hasuf/.cabal/bin:/c/ghcup/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```

After ` source ./emsdk_env.sh`:

```
/c/Users/hasuf/emsdk:/c/Users/hasuf/emsdk/upstream/emscripten:/c/Users/hasuf/emsdk/node/16.20.0_64bit/bin:/c/Users/hasuf/.cabal/bi/n/c/ghcup/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```

You can see that it created something `/c/Users/hasuf/.cabal/bi/n/c/ghcup/bin`, which is supposed to be `/c/Users/hasuf/.cabal/bin:/c/ghcup/bin`.

**Comment by hasufell** [comment]
> emconfigure doesn't generally work on windows because its a wrapper around configure which itself is a bash shell script

Also not really true. You can run `emconfigure <some-binary>` just fine. It invokes whatever you tell it to:

https://github.com/emscripten-core/emscripten/blob/fd8d7f617faaae9f21ea98b55c6979b10ec6bce6/emconfigure.py#L52

**Comment by sbc100** [comment]
> > emconfigure doesn't generally work on windows because its a wrapper around configure which itself is a bash shell script
> 
> Also not really true. You can run `emconfigure <some-binary>` just fine. It invokes whatever you tell it to:
> 
> https://github.com/emscripten-core/emscripten/blob/fd8d7f617faaae9f21ea98b55c6979b10ec6bce6/emconfigure.py#L52

Technically true .   Do you have  an example that you are trying to make work?   i.e. Do you have an example of a project that you are trying to build that provides a "<some-binary>" file that is a windows executable rather than a shell script?

**Comment by MarcelZissler** [comment]
Hello I have a question which might fit into this issue, probably you @sbc100 know the answer:

I downloaded the Asset-Importer-Lib and used `emcmake cmake -DASSIMP_BUILD_ZLIB=ON ..` which works fine.
But as i wanted to move forward with `emconfigure ./configure` i get:

`emconfigure ./configure 
configure: ./configure 
emconfigure: error: ./configure failed: [WinError 2] The system cannot find the specified file`

I am on Windows and have installed MinGW. How do i get it to work and use  `emconfigure ./configure` and `emmake make`

I appreciate any help!

I've already tried using vcpkg for this, and as you suggested, I've tried to get help, but it's been very difficult so far. So i thought of trying a different approach and build assimp myself.
https://github.com/emscripten-core/emscripten/issues/20129

**Comment by sbc100** [comment]
Getting configure scripts to work on windows is going to pretty tricky, but perhaps it is possible with enough determination.   

Firstly, does `./configure` work on it own (i.e. for building the native version of the library).    What happens when you run `./configure` with out emscirpten involved at all?  I imagine you will see the same error?  

Secondly what shell are you using when you run that command?  To run the `./configure` script you probably need to be in a bash shell because the configure script itself will have `#!` at the top.

I suppose you could try running `sh ./configure` if you wanted to run from a non-bash shell.
